"""Refina terminologia: linha_de_fomento, tipo_instrumento, natureza_recurso, publico_alvo, tipo_parceria, modalidade_pessoa, data_resultado_previsto

Revision ID: 01fde58b5fdb
Revises: 4619dcdbb505
Create Date: 2026-07-29 14:38:07.120292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01fde58b5fdb'
down_revision = '4619dcdbb505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linha_de_fomento', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tipo_instrumento', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('natureza_recurso', postgresql.ARRAY(sa.String(length=50)), nullable=False))
        batch_op.add_column(sa.Column('publico_alvo', postgresql.ARRAY(sa.String(length=50)), nullable=False))
        batch_op.add_column(sa.Column('tipo_parceria', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('modalidade_pessoa', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('data_resultado_previsto', sa.Date(), nullable=True))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('data_resultado_previsto')
        batch_op.drop_column('modalidade_pessoa')
        batch_op.drop_column('tipo_parceria')
        batch_op.drop_column('publico_alvo')
        batch_op.drop_column('natureza_recurso')
        batch_op.drop_column('tipo_instrumento')
        batch_op.drop_column('linha_de_fomento')

    # ### end Alembic commands ###
