"""adiciona revisao_pendente e tabela execucoes_scraper

Revision ID: 816ff492e253
Revises: a425646e42cb
Create Date: 2026-08-10 17:15:05.833561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '816ff492e253'
down_revision = 'a425646e42cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucoes_scraper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executado_em', sa.DateTime(), nullable=False),
    sa.Column('disparado_por', sa.String(length=30), nullable=False),
    sa.Column('resumo_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        # server_default necessário: a tabela já tem registros, e um NOT NULL sem
        # default de servidor falha ao adicionar a coluna. Removido logo depois para
        # não deixar um default "escondido" no schema além do que o modelo já expressa
        # (default=False é aplicado pela aplicação, não pelo banco).
        batch_op.add_column(sa.Column('revisao_pendente', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.alter_column('revisao_pendente', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.drop_column('revisao_pendente')

    op.drop_table('execucoes_scraper')
    # ### end Alembic commands ###
