"""Adiciona status_oficial, valores em faixa (orcamento/min/max), area_principal e palavras_chave

Revision ID: a425646e42cb
Revises: 01fde58b5fdb
Create Date: 2026-07-30 19:26:42.307547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a425646e42cb'
down_revision = '01fde58b5fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_oficial', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('area_principal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('palavras_chave', postgresql.ARRAY(sa.String(length=150)), nullable=True))
        batch_op.add_column(sa.Column('orcamento_total_chamada', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_minimo_proposta', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_maximo_proposta', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.drop_column('area_conhecimento')
        batch_op.drop_column('valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('area_conhecimento', postgresql.ARRAY(sa.VARCHAR(length=150)), autoincrement=False, nullable=True))
        batch_op.drop_column('valor_maximo_proposta')
        batch_op.drop_column('valor_minimo_proposta')
        batch_op.drop_column('orcamento_total_chamada')
        batch_op.drop_column('palavras_chave')
        batch_op.drop_column('area_principal')
        batch_op.drop_column('status_oficial')

    # ### end Alembic commands ###
